# **Data Types in Python**


In [ ]:
# Python is dynamically typed, meaning you don't need to declare variable types explicitly.
# The interpreter infers the type at runtime.

# Example in Python:
x = 10  # x is an integer
x = "Hello"  # x is now a string


# In contrast, C is statically typed, requiring type declarations.

# Example in C:
# int x = 10; // x is declared as an integer
# x = "Hello"; // This would result in a compilation error

### **Integer**

In [3]:
# Integer
integer_variable = 10
print(type(integer_variable))  # Output: <class 'int'>

<class 'int'>


### **String**

In [16]:
# String
string_with_single_quotes = 'Hello, world!'
string_with_double_quotes = "Hello, world!"
string_with_apostrophe = "It's a beautiful day."

print(string_with_single_quotes)
print(string_with_double_quotes)
print(string_with_apostrophe)

Hello, world!
Hello, world!
It's a beautiful day.


In [ ]:
# String
string_with_single_quotes = 'Hello, world!'
string_with_double_quotes = "Hello, world!"
string_with_apostrophe = 'It\'s a beautiful day.'

print(string_with_single_quotes)
print(string_with_double_quotes)
print(string_with_apostrophe)

# Different ways to print in Python

# 1. Using the print() function with a string literal
print("Welcome to SRH Campus Hamburg!")

# 2. Using f-strings (formatted string literals)
message = "Welcome to SRH"
print(f"{message}")

# 3. Using the % operator (older style formatting)
message = "Welcome to SRH Campus Hamburg!"
print("Message: %s" % message)

# 4. Using the str.format() method
message = "Welcome to SRH Campus Hamburg!"
print("{}".format(message))

# String methods such as replace, endswith (Independent Reading)!

Hello, world!
Hello, world!
It's a beautiful day.
Welcome to SRH Campus Hamburg!
Welcome to SRH
Message: Welcome to SRH Campus Hamburg!
Welcome to SRH Campus Hamburg!


In [ ]:
# Boolean
boolean_variable = True
print(type(boolean_variable))  # Output: <class 'bool'>

<class 'bool'>


### **List**

In [4]:
# Create a list (define a list)
list_variable = [1, 2, 3, "a", "b", "c"] # List is mutable, indexed iterable
print(type(list_variable))  # Output: <class 'list'>
print(len(list_variable)) # Output: 6

<class 'list'>
6


In [17]:
# Using for loop to creat a list
squares = []

for i in range(1, 7):
    squares.append(i * i)

print(squares)

[1, 4, 9, 16, 25, 36]


In [8]:
# Generate a list using range function
my_list = list(range(10))      # Iterable vs list?
print(my_list)  # Output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Check the type of the list
print(type(my_list))  # Output: <class 'list'>


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [9]:
# Check the type of the elements in the list (first element as an example by indexing it)
if my_list is not None:
  print(type(my_list))  # Output: <class 'int'>
else:
  print("List has None value")

<class 'list'>


In [ ]:
# List comprehension
L = [1, 2, 3, 4, 5]

L2 = []   # Non-Pythonic
for i in L:
  L2.append(i**2)

# "List Comprehension" to create a new list with each element squared
L2 = [x**2 for x in L]

print(L2)


# -> Search for list comprehension example online with two levels for loop 
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print([[j for j in inner_list] for inner_list in list_of_lists]) # -> try ctlr+d to rename i at once 

# L2 = [] # reset L2
# for x in L:  # traditional way of looping (not Pythonic)
#   L2.append(x**2)

print(L2)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 4, 9, 16, 25]


In [ ]:
# List comprehension with condition example: only include even numbers
L = [1, 2, 3, 4, 5]

L3 = [x for x in L if x % 2 == 0]

print(L3)  # Output: [2, 4]

[2, 4]


### **Tuple**

In [10]:
# A tuple is an ordered, immutable collection of elements.
# Immutable means that once a tuple is created, you cannot change its contents.

tuple_variable = (1, 2, 3, "a", "b", "c")
print(type(tuple_variable))  # Output: <class 'tuple'>

# Accessing elements through indexing
print(tuple_variable[0])  # Output: 1
print(tuple_variable[3])  # Output: "a"

# Tuple Length
print(len(tuple_variable))  # Output: 6

<class 'tuple'>
1
a
6


In [ ]:
# Check for element existence
tuple_variable = (1, 2, 3, "a", "b", "c")
print(1 in tuple_variable)  # Output: True
print(4 in tuple_variable)  # Output: False

True
False


In [12]:
# Tuple Concatenation
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
new_tuple = tuple1 + tuple2
print(new_tuple)  # Output: (1, 2, 3, 4, 5, 6)

# Tuple Repetition
tuple3 = (1, 2)
repeated_tuple = tuple3 * 3
print(repeated_tuple)  # Output: (1, 2, 1, 2, 1, 2)

(1, 2, 3, 4, 5, 6)
(1, 2, 1, 2, 1, 2)


In [ ]:
# Tuple Unpacking
tuple_variable = (1, 2, 3, "a", "b", "c")
a, b, *rest = tuple_variable
print(a)  # Output: 1
print(b)  # Output: 2
print(rest)  # Output: [3, 'a', 'b', 'c']
print(type(rest))

b
c
[1, 2, 3, 'a']
<class 'list'>


In [ ]:
# Related method to Tuples in Python 
# Tuples have limited methods compared to lists because they are immutable.
# count() : counts the occurrences of an element
print(tuple_variable.count(2))  # Output: 1

# index() : returns the index of the first occurrence of an element
print(tuple_variable.index("b"))  # Output: 4

1
4


In [19]:
tuple_variable = (1, 2, 3, "a", "b", "c")

# Changing a typle afrer creating it raises an error
tuple_variable[0] = 10

TypeError: 'tuple' object does not support item assignment

### **Dictionary**

In [ ]:
dictionary_variable = {"name": "Markus Doe", "age": 30, "city": "Hamburg"}
print(type(dictionary_variable))  # Output: <class 'dict'>

# Accessing values using keys
print(dictionary_variable["name"])  # Output: Markus Doe
print(dictionary_variable["age"])   # Output: 30

# Getting all keys
print(dictionary_variable.keys())  # Output: dict_keys(['name', 'age', 'city'])
print("Returns keys of a dict. as a list", list(dictionary_variable.keys()))

# Getting all values
print(dictionary_variable.values())  # Output: dict_values(['Markus Doe', 30, 'New York'])

# Getting all key-value pairs as tuples
print(dictionary_variable.items())  # Output: dict_items([('name', 'Markus Doe'), ('age', 30), ('city', 'New York')])


<class 'dict'>
Markus Doe
30
dict_keys(['name', 'age', 'city'])
Returns keys of a dict. as a list ['name', 'age', 'city']
dict_values(['Markus Doe', 30, 'Hamburg'])
dict_items([('name', 'Markus Doe'), ('age', 30), ('city', 'Hamburg')])


In [24]:
# Adding a new key-value pair
dictionary_variable["occupation"] = "Software Engineer"
print(dictionary_variable)

# Modifying an existing value
dictionary_variable["age"] = 31
print("dictionary_variable: ", dictionary_variable)

{'name': 'Markus Doe', 'age': 30, 'city': 'Hamburg', 'occupation': 'Software Engineer'}
dictionary_variable:  {'name': 'Markus Doe', 'age': 31, 'city': 'Hamburg', 'occupation': 'Software Engineer'}


In [ ]:
# Unpacking using individual key-value pairs:
name, age, city = dictionary_variable['name'], \
                  dictionary_variable['age'], \
                  dictionary_variable['city']
print(name, age, city)

# Unpacking only certain keys
new_dict = {
  **dictionary_variable,
  'country': 'Germany'
  } # Merges values from my_dict into new_dict, add country:USA

print(new_dict)


Markus Doe 31 Hamburg
{'name': 'Markus Doe', 'age': 31, 'city': 'Hamburg', 'occupation': 'Software Engineer', 'country': 'Germany'}


In [20]:

# Nested dictionary unpacking
my_nested_dict = {
  'user': {'name': 'Jane', 'age': 25},
  'address': {'city': 'London'}
  }

user_name, user_age = my_nested_dict['user'].values()
print(user_name, user_age) # Output: Jane 25

Jane 25


In [ ]:
# Removing a key-value pair
dictionary_variable = {"name": "Markus Doe", "age": 30, "city": "Hamburg"}
del dictionary_variable["city"]
print("dictionary_variable: ", dictionary_variable)

dictionary_variable:  {'name': 'Markus Doe', 'age': 30}


In [ ]:
# Looping through a dictionary without list comprehension (Non Pythonic)
my_dict = {'a': 1, 'b': 2, 'c': 3}

for key, value in my_dict.items():
  print(f"Key: {key}, Value: {value}")

# Nested dictionary unpacking
my_nested_dict = {
  'user': {'name': 'Jane', 'age': 25},
  'address': {'city': 'London'}
  }

user_name, user_age = my_nested_dict['user'].values()
print(user_name, user_age) # Output: Jane 25
# Looping through a dictionary with list comprehension
# Create a list of values
values = [value for key, value in my_dict.items()]
print(values)

# Creating a dictionary from Tuple
my_tuple = (('name', 'Markus Doe'), ('age', 30), ('city', 'Hamburg'))
my_dict = dict(my_tuple)
my_dict

Key: a, Value: 1
Key: b, Value: 2
Key: c, Value: 3
[1, 2, 3]


{'name': 'Markus Doe', 'age': 30, 'city': 'Hamburg'}

### **Set**

In [ ]:
# A set is an unordered collection of unique elements.
# It means that a set can't contain duplicate elements.
# Sets are useful for tasks like removing duplicates from a list or 
#  checking for membership in a collection.

# Creating a set:
my_set = {1, 2, 3, 4, 5}
print(my_set)  # Output: {1, 2, 3, 4, 5}
print(type(my_set))  # Output: <class 'set'>

# Adding elements to a set:
my_set.add(6)
print(my_set) # Output: {1, 2, 3, 4, 5, 6}

# Removing elements from a set:
my_set.remove(3)
print(my_set) # Output: {1, 2, 4, 5, 6}

{1, 2, 3, 4, 5}
<class 'set'>
{1, 2, 3, 4, 5, 6}
{1, 2, 4, 5, 6}


In [ ]:
# Set operations:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Union (combines elements from both sets):
union_set = set1.union(set2)
print(union_set) # Output: {1, 2, 3, 4, 5}

# Intersection (finds common elements):
intersection_set = set1.intersection(set2)
print(intersection_set) # Output: {3}


# Difference (elements in set1 but not in set2):
difference_set = set1.difference(set2)
print(difference_set) # Output: {1, 2}

{1, 2, 3, 4, 5}
{3}
{1, 2}


### **None**

In [ ]:
my_variable = None
print(my_variable)  # Output: None
print(type(my_variable))  # Output: <class 'NoneType'>


# Example 2: Function returning None (common in production level code!)
def my_function(x, y):
  if x > y:
    return x
  else:
    return None

result = my_function(5, 10)
print(result)  # Output: None

None
<class 'NoneType'>
None


### **NumPy**

In [ ]:
# Numpy is a package of a more efficient storage and data operations, as the arrays grow larger in size,
#  than lists
# It is a Package! Mind the term.
import numpy as np
np.__version__  # Dunder/Magic methods Example (find more online and get familar with)

'2.2.1'

In [ ]:
# Attributes of NumPy Arrays
import numpy as np
arr = np.random.randint(0, high=10, size=(3, 4))
print(arr, '\n')
print(type(arr))  # Output: <class 'numpy.ndarray'>
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)
print("Size:", arr.size)

# Indexing of Arrays
print("Element at (1, 2):", arr[1, 2])
print("Element at (-1, 2):", arr[-1, 2])

[[9 5 2 1]
 [0 5 9 4]
 [7 0 5 4]] 

<class 'numpy.ndarray'>
Shape: (3, 4)
Data type: int32
Number of dimensions: 2
Size: 12
Element at (1, 2): 9
Element at (-1, 2): 5


**NumPy Data Types Summary (Self-reading)**

| Category            | NumPy Data Type | Description                                      | Bit Width | Range                                  |
|---------------------|------------------|--------------------------------------------------|-----------|----------------------------------------|
| **Boolean**         | `bool_`          | Boolean (True or False)                          | 8-bit     | `True` or `False`                      |
| **Signed Integer**  | `int8`           | Integer (-128 to 127)                            | 8-bit     | -128 to 127                            |
|                     | `int16`          | Integer (-32,768 to 32,767)                      | 16-bit    | -32,768 to 32,767                      |
|                     | `int32`          | Standard signed integer                          | 32-bit    | -2,147,483,648 to 2,147,483,647        |
|                     | `int64`          | Large signed integer                             | 64-bit    | -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 |
| **Unsigned Integer**| `uint8`          | Unsigned integer (0 to 255)                      | 8-bit     | 0 to 255                               |
|                     | `uint16`         | Unsigned integer (0 to 65,535)                   | 16-bit    | 0 to 65,535                            |
|                     | `uint32`         | Unsigned integer (0 to 4.29 billion)             | 32-bit    | 0 to 4,294,967,295                     |
|                     | `uint64`         | Unsigned integer (0 to 18.4 quintillion)         | 64-bit    | 0 to 18,446,744,073,709,551,615        |
| **Floating Point**  | `float16`        | Half-precision float                             | 16-bit    | ±5.96×10⁻⁸ to ±65,504                  |
|                     | `float32`        | Single-precision float                           | 32-bit    | ±1.18×10⁻³⁸ to ±3.4×10³⁸               |
|                     | `float64`        | Double-precision float (default in NumPy)        | 64-bit    | ±2.23×10⁻³⁰⁸ to ±1.80×10³⁰⁸            |
| **Complex Numbers** | `complex64`      | Two 32-bit floats: real and imaginary parts      | 64-bit    | Based on `float32` range               |
|                     | `complex128`     | Two 64-bit floats: real and imaginary parts      | 128-bit   | Based on `float64` range               |
| **Text**            | `str_`           | Fixed-length Unicode string                      | -         | -                                      |
| **Binary**          | `bytes_`         | Fixed-length raw byte string                     | -         | -                                      |

**Note:** NumPy types are suffixed with underscores (`_`) to distinguish them from Python built-in types.

Find more details and data types in [Numpy documentation](https://numpy.org/doc/stable/user/basics.types.html?utm_source=chatgpt.com)


In [ ]:
# Slicing of Arrays
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(arr, '\n')
print(type(arr), '\n')    # Output: <class 'numpy.ndarray'>

print("First two rows:\n", arr[:2]) #  Output: [[0 1 2 3]
                                    #          [4 5 6 7]]

print("Last row:\n", arr[-1]) #  Output: [8, 9, 10, 11]

print("Last two columns of the second row:\n", arr[1, -2:])    # Output: [6 7]

print("First row with first column :\n", arr[0, 0])    # Output: [0]

print("Every other element in the first row:", arr[0, 0::2]) # Output: [0 2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

<class 'numpy.ndarray'> 

First two rows:
 [[0 1 2 3]
 [4 5 6 7]]
Last row:
 [ 8  9 10 11]
Last two columns of the second row:
 [6 7]
First row with first column :
 0
Every other element in the first row: [0 2]


In [ ]:
# Reshaping of Arrays
arr_reshaped = arr.reshape(6, 2)
print("Reshaped array:\n", arr_reshaped)

Reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
# Vector vs Matrix in Numpy
# Vector Example
v = np.array([0, 1, 2, 3, 4])
print("v is an ndarray vector:", v)
print(type(v))   # Output: <class 'numpy.ndarray'>
print("Shape:", v.shape)    # Output: Shape: (5,)
print(v.ndim)    # Output: 1
#Transpose
print(v.T)       # Output: [0 1 2 3 4] — no visible change
print('\n')

# Matrix Example
m = np.array([[0, 1, 2, 3, 4]])
print("m is an ndarray matrix:", m)
print(type(m))   # Output: <class 'numpy.ndarray'>
print(m.shape)   # Output: (1, 5)
print(m.ndim)    # Output: 2

# Transpose
print("The transpose of the matrix m:\n", m.T)
print('\n')

# Matrix Example 2
m2 = np.array([[1, 2, 3], [4, 5, 6]])
print(m2.shape)   # Output: (2, 3)
print(m2.ndim)    # Output: 2
# Transpose
print("The transpose of the matrix m2:\n", m2.T)       # Output: [[1 4], [2 5], [3 6]]


v is an ndarray vector: [0 1 2 3 4]
<class 'numpy.ndarray'>
Shape: (5,)
1
[0 1 2 3 4]


m is an ndarray matrix: [[0 1 2 3 4]]
<class 'numpy.ndarray'>
(1, 5)
2
The transpose of the matrix m :
 [[0]
 [1]
 [2]
 [3]
 [4]]


(2, 3)
2
The transpose of the matrix m2:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 1-D vs 2-D Vector in Numpy

# 1-D Example
v = np.array([1, 2, 3])
print(v.shape)

# 2-D Examples
col_vector = v.reshape(3, 1)  # Column vector: shape (3, 1)
print(col_vector.shape)

row_vector = v.reshape(1, 3)  # Row vector: shape (1, 3)
print(row_vector.shape)

# A row vector has shape (1, n) and is a 2D matrix with one row.
# A column vector has shape (n, 1) and is a 2D matrix with one column.

(3,)
(3, 1)
(1, 3)


In [ ]:
# Joining and Splitting of Arrays
arr1 = np.random.randint(0, 5, size=(2, 3))
arr2 = np.random.randint(5, 10, size=(2, 3))

print('arr1:',  arr1, '\n')
print('arr2:',  arr2, '\n')

# Concatenate along rows (vertical stacking)
arr_concat_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:\n", arr_concat_rows)

# Concatenate along columns (horizontal stacking)
arr_concat_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along columns:\n", arr_concat_cols)

# Splitting the array into two equal parts along the rows
arr_split_rows = np.split(arr_concat_rows, 2, axis=0)
print("Split along rows:\n", arr_split_rows)

# Splitting the array into three equal parts along the columns
arr_split_cols = np.split(arr_concat_cols, 3, axis=1)
print("Split along columns:\n", arr_split_cols)

arr1: [[4 1 1]
 [3 3 0]] 

arr2: [[6 8 7]
 [8 8 5]] 

Concatenated along rows:
 [[4 1 1]
 [3 3 0]
 [6 8 7]
 [8 8 5]]
Concatenated along columns:
 [[4 1 1 6 8 7]
 [3 3 0 8 8 5]]
Split along rows:
 [array([[4, 1, 1],
       [3, 3, 0]], dtype=int32), array([[6, 8, 7],
       [8, 8, 5]], dtype=int32)]
Split along columns:
 [array([[4, 1],
       [3, 3]], dtype=int32), array([[1, 6],
       [0, 8]], dtype=int32), array([[8, 7],
       [8, 5]], dtype=int32)]


**Copying in Python**

In [ ]:
# Example showing how changing arrays of the same reference changes the original array
arr1 = np.array([1, 2, 3])
arr2 = arr1  # arr2 now refers to the same array as arr1
arr2[0] = 10
print(f"arr1: {arr1}", '\n')  # Output: arr1: [10  2  3]  (arr1 is also changed)

# Check the memory address for arr1 and arr2
print("Memory address of a:", hex(id(arr1)))
print("Memory address of b:", hex(id(arr2)))


arr1: [10  2  3] 

Memory address of a: 0x159ff164270
Memory address of b: 0x159ff164270


In [ ]:
# Example showing how copying arrays prevents changing the original
arr1 = np.array([1, 2, 3])

arr2 = arr1.copy()  # arr2 is a new copy of arr1
arr2[0] = 10
print(f"arr1: {arr1}")  # Output: arr1: [1 2 3] (arr1 remains unchanged)
print(f"arr2: {arr2}")  # Output: arr2: [10  2  3]

# Check the memory address for arr1 and arr2
print("Memory address of a:", hex(id(arr1)))
print("Memory address of b:", hex(id(arr2)))

arr1: [1 2 3]
arr2: [10  2  3]
Memory address of a: 0x159ff164c90
Memory address of b: 0x159ff164b70


In [ ]:
# In case of a Matrix (list of lists), copy does not work, instead, .deepcopy(..) should be used

import copy
a = [1, [2, 3]]
b = copy.deepcopy(a)

# test the example yourself ...

**A simple Function Example in Python**

In [ ]:
# Functions are created for reusing a block of code.
def add(a, b):
    return a + b

result = add(3, 5)
print(result)   # 8

8


**Summation in Numpy**

In [ ]:
# sum
big_array = np.random.rand(100000)
%timeit sum(big_array)  # %timeit is an example of Magic Functions for Jupyter/.ipynb files
%timeit np.sum(big_array)

# In .py files, use time library as follows:
import time
start = time.time()
print("hello") # or any function/method implementation
end = time.time()
print(end - start)

# alternative to 'time' import, and -even better-, is perf_counter (https://docs.python.org/3/library/time.html#time.perf_counter  


9.79 ms ± 496 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
46.5 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Min, Max
np.min(big_array), np.max(big_array)

(6.611145074497671e-06, 0.9999866913836751)

In [ ]:
# Aggergation Functions (all, any, argmax, argmin)
arr = np.array([1, 2, 3, 4, 5, 0])

# .any() checks if any element in the array is True
print(arr > 2)  # Output: [False False  True  True  True False]
print((arr > 2).any())  # Output: True

# .all() checks if all elements in the array are True
print(arr > 0)  # Output: [ True  True  True  True  True False]
print((arr > 0).all())  # Output: False

# argmax and argmin
arr2 = np.array([1, 5, 2, 8, 3])

# argmax returns the index of the maximum element
print(np.argmax(arr2))  # Output: 3 (index of 8)

# argmin returns the index of the minimum element
print(np.argmin(arr2))  # Output: 0 (index of 1)

[False False  True  True  True False]
True
[ True  True  True  True  True False]
False
3
0


In [ ]:
# Broadcasting in Numpy

import numpy as np

# Case 1: Scalar and Array
# Broadcasting a scalar to an array
a = np.array([1, 2, 3])
b = 2
c = a + b  # Adds 2 to each element of 'a'
print(f"Case 1:\n{c}")

# Case 2: Array and Array (Compatible Shapes)
# Broadcasting two arrays with compatible shapes
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([1, 2, 3])  # Shape (3,)
c = a + b  # Adds 'b' to each row of 'a'
print(f"\nCase 2:\n{c}")


# Case 3: Array and Array (One Dimension with Size 1)
# Broadcasting when one dimension has size 1
a = np.array([[1], [2], [3]])  # Shape (3, 1)
b = np.array([1, 2, 3])  # Shape (3,)
c = a + b  # shape (3, 3) -> 'a' is expanded along the second dimension to match 'b'
print(f"\nCase 3:\n{c}")
d = b + a
print(f"d:", d)

# Case 4: Error Case (Incompatible Shapes), an example to Error handling in Python
# Trying to broadcast incompatible shapes will raise an error
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([1, 2])  # Shape (2,)
try:
    c = a + b
except ValueError as e:
   print(f"\nCase 4 Error:\n{e}")


# Case 5: Common Error - Unintended Broadcasting
# This is a common source of error: unintentionally broadcasting when you don't intend to
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([10, 20, 30])  # Shape (3,)
c = a * b  # Element-wise multiplication, but often leads to errors if not intended
print(f"\nCase 5:\n{c}")


# Case 6: More Complex Broadcasting
# Demonstrating more complex broadcasting with higher dimensions
a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 1)


c = a + b  # 'b' is broadcasted along the first and third dimensions to match 'a'
print("\nCase 6:\n")
print(f"\na.shape:\n{a.shape}")
print(f"\nb.shape:\n{b.shape}")
print(f"\nc.shape:\n{c.shape}")

print("a:", a)
print('\n')
print("b:", b)
print('\n')
print("c:", c)



Case 1:
[3 4 5]

Case 2:
[[2 4 6]
 [5 7 9]]

Case 3:
[[2 3 4]
 [3 4 5]
 [4 5 6]]
d: [[2 3 4]
 [3 4 5]
 [4 5 6]]

Case 4 Error:
operands could not be broadcast together with shapes (2,3) (2,) 

Case 5:
[[ 10  40  90]
 [ 40 100 180]]

Case 6:


a.shape:
(2, 3, 4)

b.shape:
(3, 1)

c.shape:
(2, 3, 4)
a: [[[0.47427999 0.24588972 0.57270678 0.36841528]
  [0.47771364 0.01651359 0.13123487 0.31552545]
  [0.61919472 0.74062358 0.08878145 0.2920786 ]]

 [[0.26313836 0.13200816 0.33179022 0.05607799]
  [0.99829075 0.0155171  0.88287479 0.46181883]
  [0.01637759 0.94799353 0.32804246 0.57996016]]]


b: [[0.89684812]
 [0.19208929]
 [0.84279123]]


c: [[[1.37112811 1.14273783 1.46955489 1.2652634 ]
  [0.66980293 0.20860288 0.32332417 0.50761474]
  [1.46198595 1.58341481 0.93157268 1.13486983]]

 [[1.15998647 1.02885628 1.22863834 0.95292611]
  [1.19038005 0.20760639 1.07496408 0.65390812]
  [0.85916882 1.79078476 1.17083369 1.42275139]]]
